name: release_linux_musl

on: workflow_dispatch

jobs:
  release_linux_musl:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        go-version: [ '1.22' ]
    name: Release
    runs-on: ${{ matrix.platform }}
    steps:

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: |
          bash build.sh release linux_musl

      - name: Release
        uses: actions/upload-artifact@v4
        with:
          name: alist
          path: build