name: release

on: workflow_dispatch

jobs:
  release:

    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [1.19]
    name: Release
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          docker pull techknowlogick/xgo:latest
          go install src.techknowlogick.com/xgo@latest
          sudo apt install upx

      - name: Build
        run: |
          bash build.sh release

      - name: Release
        uses: actions/upload-artifact@v2
        with:
          name: alist
          path: build